modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="snowshoeslogo.png"
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]] #optional
    modId="geckolib" #mandatory
    mandatory=true #mandatory
    versionRange="[4.2,)" #mandatory
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
